version: '3'
services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=sf4
      - POSTGRES_USER=sf4
      - POSTGRES_PASSWORD=sf4
    volumes:
      - pgdata:/var/lib/postgresql/data2
    ports:
      - "5432:5432"

  maildev:
      image: djfarrelly/maildev
      ports:
        - "1080:80"
        - "1025:25"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER= admin
      - RABBITMQ_DEFAULT_PASS= admin
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
        - "6379:6379"
    volumes:
      - redis-data:/data

  php:
    build:
        context: .
        dockerfile: ops/php-fpm/Dockerfile
    volumes:
        - ./:/var/www/sf4
        - "./ops/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    depends_on:
        - rabbitmq
        - maildev
        - redis

  web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./ops/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php

volumes:
  pgdata:
    driver: local
  redis-data:
    driver: local